name: 'Github Container Registry Build'

on:
  push:
    tags:
      - '**'
    branches:
      - '**'

env:
  ghcr_latest_tag: "${{ github.ref_type == 'tag' && ',ghcr.io/appuio/grafana-organizations-operator:latest' || '' }}"

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=true # Without this the .git directory is not present and our tests fail
          push: true
          tags: "ghcr.io/appuio/grafana-organizations-operator:${{ github.ref_name }}${{ env.ghcr_latest_tag }}"

